<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Categorie;
use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
    public function findByParentNull(Categorie $categorie = null)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->where('c.parent IS NULL');

        if ($categorie instanceof Categorie) {
            $qb->andWhere('c.id <> :id')->setParameter('id', $categorie->getId());
        }

        return $qb;
    }

    public function findByParentNotNull(Categorie $categorie = null)
    {
        $qb = $this
            ->createQueryBuilder('c')
            ->where('c.parent IS NOT NULL');

        if ($categorie instanceof Categorie) {
            $qb->andWhere('c.id <> :id')->setParameter('id', $categorie->getId());
        }

        return $qb;
    }
}
