<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Compte;

/**
 * OperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAPointerByCompte(Compte $compte)
    {
        $operationList = $this->_em
            ->createQuery(
                'SELECT o, m 
                 FROM AppBundle:Operation o
                 LEFT JOIN o.modePaiement m
                 WHERE o.dateValeur IS NULL AND o.compte = :compte
                 ORDER BY o.dateOperation DESC')
            ->setParameter('compte', $compte);

        return $operationList->getResult();
    }

    public function findPointeeByCompte(Compte $compte)
    {
        $operationList = $this->_em
            ->createQuery(
                'SELECT o, m 
                 FROM AppBundle:Operation o
                 LEFT JOIN o.modePaiement m
                 WHERE o.dateValeur IS NOT NULL AND o.compte = :compte
                 ORDER BY o.dateOperation DESC')
            ->setParameter('compte', $compte);

        return $operationList->getResult();
    }
}
